apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  labels:
    app: myapplication
data:
  my-key: test

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: k8s.gcr.io/busybox
      command: ["env"]
      envFrom:
        - configMapRef:
            name: test-config
